name: Sincronizar docs com Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v7

      - name: Baixar Wiki
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sincronizar documentação
        run: |
          find wiki -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          cp -r docs/. wiki/

      - name: Atualizar Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .

          if git diff --cached --quiet; then
            echo "Wiki já está atualizada."
          else
            git commit -m "docs: atualiza Wiki automaticamente"
            git push
          fi
